name: Deploy to Firebase

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときにトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.jsをセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Firebase CLIがサポートするNode.jsバージョン

      # Firebase CLIのインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Firebaseデプロイ
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting,functions
